export const routesMock = [
  {
    routeId: 1,
    imageUrl: "",
    title: "Architecture Walk from Central to Wan Chai",
    distance: 5.75,
    duration: "2.5 - 3 hrs",
    userName: "Sean Kwok",
    userProfileImg: "",
    checkpointNumber: 1,
    tags: ["Tag", "Tag"],
    start: "Central",
    end: "Wan Chai",
    city: "Hong Kong SAR",
  },
  {
    routeId: 2,
    imageUrl: "",
    title: "Architecture Walk from Central to Wan Chai",
    distance: 5.75,
    duration: "2.5 - 3 hrs",
    userName: "Sean Kwok",
    userProfileImg: "",
    checkpointNumber: 2,
    tags: ["Tag", "Tag"],
    start: "Central",
    end: "Wan Chai",
    city: "Hong Kong SAR",
  },
  {
    routeId: 3,
    imageUrl: "",
    title: "Architecture Walk from Central to Wan Chai",
    distance: 5.75,
    duration: "2.5 - 3 hrs",
    userName: "Sean Kwok",
    userProfileImg: "",
    checkpointNumber: 3,
    tags: ["Tag", "Tag"],
    start: "Central",
    end: "Wan Chai",
    city: "Hong Kong SAR",
  },
];
